name: Build

on: push

jobs:
  build:
    environment: build-env
    runs-on: ubuntu-latest
    needs: date-check
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.3.3'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build
        run:
          bundle exec middleman build --build-dir=site

      - name: Deploy
        env:
          SERVER_IP_ADDRESS: dev.moysklad.ru
          APP_PREFIX: api-vendor
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          touch ~/.ssh/config && chmod 600 ~/.ssh/config
          echo -e "Host ${SERVER_IP_ADDRESS}\n\tStrictHostKeyChecking no\nPort 22\n" >> ~/.ssh/config
          ssh-add - <<< "$DEPLOY_KEY"
          ssh app@${SERVER_IP_ADDRESS} pwd
          rsync -r --delete-after --quiet site/ app@${SERVER_IP_ADDRESS}:./${APP_PREFIX}
